[package]
name = "space-thumbnails-windows-dll"
version = "0.1.2"
edition = "2021"

[dependencies]
windows = "0.34"
space-thumbnails-windows = { path = "../windows" }
winreg = "0.10"

[lib]
crate-type = ["cdylib"]
