[package]
name = "space-thumbnails-windows-installer"
version = "1.0.0"
edition = "2021"

[dependencies]
space-thumbnails-windows = { path = "../windows" }
windows = "0.34.0"
ureq = "2.4"
zip = "0.6"
